approvedGitRepositories:
  - "**"

defaultSemverRangePrefix: ""

enableConstraintsChecks: true

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 6000

npmPreapprovedPackages:
  - react
  - react-native
  - "@react-native/*"
  - react-native-worklets
  - react-native-webgpu
  - react-native-enriched-markdown
  - react-native-sse
  - remend
  - "@react-navigation/*"

tsEnableAutoTypes: false
