enableGlobalCache: false

nodeLinker: node-modules

defaultSemverRangePrefix: ''

enableConstraintsChecks: true

enableScripts: false

npmMinimalAgeGate: 6000
npmPreapprovedPackages:
  - 'react'
  - 'react-native'
  - '@react-native/*'
  - 'react-native-worklets'

tsEnableAutoTypes: false
